
services:
  # 1. База данных PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: boxmanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post
      POSTGRES_DB: boxmanager
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. PgAdmin для просмотра БД через браузер
  pgadmin:
    image: dpage/pgadmin4
    container_name: boxmanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  # 3. Ваше Go-приложение
  app:
    build: .
    container_name: boxmanager_app
    ports:
      - "9091:9091"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker 
    restart: always

volumes:
  pg_data: